{# docblock for a C language file}
{top}{newline}{up}
/**{newline}
 * @file   {filename}{newline}
 * @brief  [small explanation]{newline}
 * @author Miguel I. Garcia Lopez / FloppySoftware{newline}
 *{newline}
 * This library implements [long explanation]{newline}
 *{newline}
 * Copyright (c) [year] Miguel I. Garcia Lopez / FloppySoftware{newline}
 *{newline}
 * Licensed under the GNU General Public License v3.{newline}
 *{newline}
 * http://www.floppysoftware.es{newline}
 * floppysoftware@gmail.com{newline}
 *{newline}
 * Definitions:{newline}
 * - [def]{newline}
 *{newline}
 * Revisions:{newline}
 * - [date] : [reason]{newline}
 *{newline}
 */{newline}
{top}{down}{right:11}
