{top}{cr}{up}
/**{cr}
 * @file   {filename}{cr}
 * @brief  [small explanation]{cr}
 * @author Miguel I. Garcia Lopez / FloppySoftware{cr}
 *{cr}
 * This library implements [long explanation]{cr}
 *{cr}
 * Copyright (c) [year] Miguel I. Garcia Lopez / FloppySoftware{cr}
 *{cr}
 * Licensed under the GNU General Public License v3.{cr}
 *{cr}
 * http://www.floppysoftware.es{cr}
 * floppysoftware@gmail.com{cr}
 *{cr}
 * Definitions:{cr}
 * - [def]{cr}
 *{cr}
 * Revisions:{cr}
 * - [date] : [reason]{cr}
 *{cr}
 */{cr}
{top}{down}{right:11}
