call make te_cpc3
call make te_kp
call make te_mur
call make te_pcw
call make te_spec
call make te_tak
call make te_ws100
call make te_ansi
call make te_px8
call make te_apple
call make te_c128
call make te_sam
